### ISSUE TITLE
Feature request: Use per project config file instead of a global config?

### ISSUE THREAD

**Issue by sgon00** [vrajafraja/context-switcher#2]
Hi, I constantly change working PCs and move project paths etc... With current global config file for one vscode instance, I won't be able to restore context after changing working PC or move the project directory path. I am wondering if this extension can support per project config file somehow (for example: `/project/.vscode/context-switcher.json` overrides global config). If this can be done and then the per project config file stores relative path instead of absolute path, so that I don't need to care about the project name and path anymore. Thanks a lot.

**Comment by vrajafraja** [comment]
Hi, sorry for waiting. Extension is now updated. Each workspace will now have its own context-switcher.json, where files are stored with relative path. There is a function called **Load context from legacy storage** for migrating existing contexts from old storage with absolute path to the new one.
