### ISSUE TITLE
When trying to load context unable to open files

### ISSUE THREAD

**Issue by Sunil23391** [vrajafraja/context-switcher#3]
![context switch error](https://user-images.githubusercontent.com/12194923/79423824-e46b6e80-7fdc-11ea-9d0c-75dad889ab6c.JPG)

**Comment by vrajafraja** [comment]
Hello, 
thank you for using this extension, I am glad to see someone else is actually using  it :) 

Do you have latest version of extension? 
Does the file exist? 
Is it a problem with all files or only this one? 

There is a new system of storing files relative to workspace path.
